name: hello

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository 
        uses: actions/checkout@v4

      - name: list fil
        run: ls

      - name: show datess
        run: date

      - name: git version
        run: git --version

      - name: Print hello message
        run: echo "Hello, world!"

    
          