name: deploy
on: 
  push:
    branches:
      - main

    workflow-dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: "hello"
        run: echo "complete the first deployment"
          